### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by Randall71** [achorein/expo-share-intent-demo#1]
Before all, thanks for take your time to made it easy to use this feature with Expo.
I clone the project and configure it with EAS with a paid apple developer account but i can't get the build working on EAS.

One thing also that i don't understand is that before launching the build, expo detect two target for the share extension, is this correct ? 

![Capture d’écran (330)](https://github.com/achorein/expo-share-intent-demo/assets/51382079/e58c6800-f42b-4f6e-b580-e15199d78b2a)

[xcode-build-04c8eb81-0e39-4e55-97fb-7b2ce3a245d8.log](https://github.com/achorein/expo-share-intent-demo/files/12444334/xcode-build-04c8eb81-0e39-4e55-97fb-7b2ce3a245d8.log)

**Comment by achorein** [comment]
I confirm, you should have only one "ShareExtension Target".
the problem seems to come from the `npx eas-cli build --platform ios` auto-configuration of eas build.

in your `app.json` you only need this part :
```
    "extra": {
      "eas": {
        "projectId": "xxxx-xxx-xxx-xxx-xxxxxx"
      }
    }
```

You must remove the experimental build config generated :
```
        "build": {
          "experimental": {
            "ios": {
              "appExtensions": [
                {
                  "targetName": "ShareExtension",
                  "bundleIdentifier": "com.example.exposhareintentdemo.share-extension",
                  "entitlements": {
                    "com.apple.security.application-groups": [
                      "group.com.example.exposhareintentdemo"
                    ]
                  }
                }
              ]
            }
          }
        },
```

**Comment by Randall71** [comment]
This work perfectly now , i can be able to share text or url with the app.

**Comment by Randall71** [comment]
I think i can close this issue and update the readme to let other people make it right the first time what do you think about it ? 

Also,can i know if you plan to add support for Android to the patch, this would be very awesome.

**Comment by achorein** [comment]
Great !
I just add the initial eas build config to the project for new comers, should solve the problem.

About android i have a little [patch](https://gist.github.com/achorein/d7a2c84a0b140afc699a90494131ced1) but only tested with Expo SDK 46. Need some work on `react-native-receive-sharing-intent` side to get it working in Expo 49.

I look into it when I have time

**Comment by achorein** [comment]
@Randall71 FYI, I add a new branch with Android working in Expo46 https://github.com/achorein/expo-share-intent-demo/tree/expo46

**Comment by achorein** [comment]
after more test, got a version working with Expo 48, merge to the main branch.

**Comment by Randall71** [comment]
you are amazing. 
I tested the new version specially for the SDK 47 but the `android tricks` part are a limitation for now to build this properly with the managed workflow. i think customize this step with a plugin would be the missing piece

**Comment by achorein** [comment]
Sure, should be great to have a single plugin doing all that stuff. Already working on it, but that take more time

**Comment by Randall71** [comment]
@achorein great to know, for this and the support for sharing files, i am definitely ready to offer you some coffee 🔥🔥

**Comment by achorein** [comment]
for the joke, i added the coffee link in the readme 🙏 😄

**Comment by Randall71** [comment]
And I was happy to follow it 😄👍
