### ISSUE TITLE
How did you manage to install expo-config-plugin-ios-share-extension under Expo 49?

### ISSUE THREAD

**Issue by croepke** [achorein/expo-share-intent-demo#12]
I have been looking at your code and was surprised how you were able to install the expo-config-plugin-ios-share-extension? Even when trying to install it (in my own repo) I immediately get a version conflict:

```
npm ERR! Found: react-native@0.72.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.72.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.69.4" from expo-config-plugin-ios-share-extension@0.0.4
```

Is there any config I'm overlooking?

**Comment by achorein** [comment]
Indeed, it seems to have some issue with `npm` (`npm install`).
I'm using Yarn and have no problem that way.

I added the overrides into `package.json` :
```
  "overrides": {
    "react-native": "0.72.4",
    "@expo/config-plugins": "~7.2.2"
  },
```

you can find the commit here for expo 49 : https://github.com/achorein/expo-share-intent-demo/commit/5ecc484bca9609a387a8776a75cb6ffd64acfbea
