### ISSUE TITLE
getting a "this screen doesn't exist" with expo router

### ISSUE THREAD

**Issue by spencerc99** [achorein/expo-share-intent-demo#14]
hi there! thanks so much for making this demo

I got as far as getting it onto my iOS device using your `useShareIntent` hook, and my app successfully shows up in the share sheet! But when I send something to the app, I'm getting a "this screen doesn't exist." I wonder if it's due to using Expo Router? Would love any ideas!

![361782FA-0020-4832-A462-B7184683ADC2_1_102_o](https://github.com/achorein/expo-share-intent-demo/assets/14796580/7977a2de-3030-4acd-962a-417b93853311)

**Comment by achorein** [comment]
👋 
Indeed my demo doesn't have a `expo-router` or `react-navigation` example.

To use `expo-router` you need to handle [Unmatched Routes ](https://docs.expo.dev/routing/error-handling/#unmatched-routes). It's the only screen where `useShareIntent` hook will work (allowing to get custom pathname).

 Here an example for `app/[...unmatched].js` file :
```js
export default function Unmatched() {
  const pathname = usePathname();
  const router = useRouter();

  const { shareIntent, resetShareIntent } = useShareIntent();

  return (
    <View style={styles.container}>
      <Text style={styles.gap}>Screen could not be found : {pathname}</Text>
      <Text style={styles.gap}>{JSON.stringify(shareIntent)}</Text>
      <Text
        onPress={() => {
          if (router.canGoBack()) {
            router.back();
          } else {
            router.replace("/");
          }
        }}
      >
        Go back.
      </Text>
    </View>
  );
}
``` 

You can also get the shareintent data from here and navigate to a specific screen with parameters to split the code.
To detect your are coming from a share intent you can test the `pathname` like that :
```js
  if (pathname?.includes(`dataurl=${Constants.expoConfig.scheme}sharekey`) && shareIntent) {
     router.replace({ pathname: 'shareintent', params: { shareIntent } })
  }
  ```

let me know if you managed to get it to work, I will update the documentation afterwards

**Comment by achorein** [comment]
We are using native code to make share intent works, so we can't use Expo Go and have to use a custom dev client, that's why the demo use `expo prebuild --no-install` command and then `expo run:ios`, instead of a simple `expo start --ios`.
More information [here](https://docs.expo.dev/workflow/customizing/#generate-native-projects-with-prebuild)

That way you can test your share intent into simulator, but that does not exempt you to test a complete build on device at the end of your development process to make sure all works as excepted :)

**Comment by achorein** [comment]
working example with expo router is now available on branch [expo49-expo-router](https://github.com/achorein/expo-share-intent-demo/tree/expo49-expo-router), enjoy !

**Comment by spencerc99** [comment]
thank you for the help! Unfortunately, I still seem to be running into issues. I followed your code in the attached branch and was able to get it running in the emulator and successfully show up in the share intent screen. However, when I share to the app, I don't seem to be getting any share intent data when using the hook strangely.

https://github.com/achorein/expo-share-intent-demo/assets/14796580/771876e5-f49b-4738-a8d0-a35e229c1c51

In my logs, I see that the share intent is being set, but it's not causing my component to re-render or that `useEffect` you use to redirect to trigger.

![image](https://github.com/achorein/expo-share-intent-demo/assets/14796580/5a976ec7-bd95-4a2c-a0c9-67c12f46799f)

this is probably an error on my part, but wondering if you have any ideas?

code below:
```
// [...unmatched.tsx]
export default function NotFoundScreen() {
  const pathname = usePathname();
  const router = useRouter();
  const { shareIntent, resetShareIntent } = useShareIntent();
  console.log("pathname", pathname, shareIntent);
  useEffect(() => {
    console.log("checking share intent", pathname, shareIntent);
    if (
      pathname?.includes(`dataurl=${Constants.expoConfig?.scheme}sharekey`) &&
      shareIntent
    ) {
      console.log("redirecting!");
      router.replace({ pathname: "/(tabs)/home", params: { shareIntent } });
      resetShareIntent();
    }
  }, [shareIntent]);

  return (
    <>
      <Stack.Screen options={{ title: "Oops!" }} />
      <View style={styles.container}>
        <Text style={styles.title}>This screen doesn't exist.</Text>

        <Text
          style={styles.linkText}
          onPress={() => {
            if (router.canGoBack()) {
              router.back();
            } else {
              router.replace({ pathname: "/(tabs)/home" });
            }
          }}
        >
          Go back.
        </Text>
      </View>
    </>
  );
}
```
and my useShareIntent hook is the same

**Comment by spencerc99** [comment]
> thank you for the help! Unfortunately, I still seem to be running into issues. I followed your code in the attached branch and was able to get it running in the emulator and successfully show up in the share intent screen. However, when I share to the app, I don't seem to be getting any share intent data when using the hook strangely.
> 
>  Screen.Recording.2023-09-20.at.3.10.03.PM.mov 
> In my logs, I see that the share intent is being set, but it's not causing my component to re-render or that `useEffect` you use to redirect to trigger.
> 
> ![image](https://user-images.githubusercontent.com/14796580/269439703-80b94f90-0532-4303-b301-18e0de134cfd.png) this is probably an error on my part, but wondering if you have any ideas?
> 
> code below:
> 
> ```
> // [...unmatched.tsx]
> export default function NotFoundScreen() {
>   const pathname = usePathname();
>   const router = useRouter();
>   const { shareIntent, resetShareIntent } = useShareIntent();
>   console.log("pathname", pathname, shareIntent);
>   useEffect(() => {
>     console.log("checking share intent", pathname, shareIntent);
>     if (
>       pathname?.includes(`dataurl=${Constants.expoConfig?.scheme}sharekey`) &&
>       shareIntent
>     ) {
>       console.log("redirecting!");
>       router.replace({ pathname: "/(tabs)/home", params: { shareIntent } });
>       resetShareIntent();
>     }
>   }, [shareIntent]);
> 
>   return (
>     <>
>       <Stack.Screen options={{ title: "Oops!" }} />
>       <View style={styles.container}>
>         <Text style={styles.title}>This screen doesn't exist.</Text>
> 
>         <Text
>           style={styles.linkText}
>           onPress={() => {
>             if (router.canGoBack()) {
>               router.back();
>             } else {
>               router.replace({ pathname: "/(tabs)/home" });
>             }
>           }}
>         >
>           Go back.
>         </Text>
>       </View>
>     </>
>   );
> }
> ```
> 
> and my useShareIntent hook is the same except i added a "[rerendering] useShareIntentHook" log at the bottom before return

well i tried again later and now it's magically working 😅 thanks for the help!

**Comment by spencerc99** [comment]
btw is there a better way to remove the auto-generated
```
 "build": {
          "experimental": {
            "ios": {
              "appExtensions": [
                {
                  "targetName": "ShareExtension",
                  "bundleIdentifier": "supply.basket.share-extension",
                  "entitlements": {
                    "com.apple.security.application-groups": [
                      "group.supply.basket"
                    ]
                  }
                }
              ]
            }
          }
        }
```
that gets adds to "eas" in `app.json`. I seem to have to do it manually each time after build. Related to #1 (let me know if you want me to open a new issue)

**Comment by spencerc99** [comment]
> > thank you for the help! Unfortunately, I still seem to be running into issues. I followed your code in the attached branch and was able to get it running in the emulator and successfully show up in the share intent screen. However, when I share to the app, I don't seem to be getting any share intent data when using the hook strangely.
> > Screen.Recording.2023-09-20.at.3.10.03.PM.mov
> > In my logs, I see that the share intent is being set, but it's not causing my component to re-render or that `useEffect` you use to redirect to trigger.
> > ![image](https://user-images.githubusercontent.com/14796580/269439703-80b94f90-0532-4303-b301-18e0de134cfd.png) this is probably an error on my part, but wondering if you have any ideas?
> > code below:
> > ```
> > // [...unmatched.tsx]
> > export default function NotFoundScreen() {
> >   const pathname = usePathname();
> >   const router = useRouter();
> >   const { shareIntent, resetShareIntent } = useShareIntent();
> >   console.log("pathname", pathname, shareIntent);
> >   useEffect(() => {
> >     console.log("checking share intent", pathname, shareIntent);
> >     if (
> >       pathname?.includes(`dataurl=${Constants.expoConfig?.scheme}sharekey`) &&
> >       shareIntent
> >     ) {
> >       console.log("redirecting!");
> >       router.replace({ pathname: "/(tabs)/home", params: { shareIntent } });
> >       resetShareIntent();
> >     }
> >   }, [shareIntent]);
> > 
> >   return (
> >     <>
> >       <Stack.Screen options={{ title: "Oops!" }} />
> >       <View style={styles.container}>
> >         <Text style={styles.title}>This screen doesn't exist.</Text>
> > 
> >         <Text
> >           style={styles.linkText}
> >           onPress={() => {
> >             if (router.canGoBack()) {
> >               router.back();
> >             } else {
> >               router.replace({ pathname: "/(tabs)/home" });
> >             }
> >           }}
> >         >
> >           Go back.
> >         </Text>
> >       </View>
> >     </>
> >   );
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and my useShareIntent hook is the same except i added a "[rerendering] useShareIntentHook" log at the bottom before return
> 
> well i tried again later and now it's magically working 😅 thanks for the help!

hmm I seem to experience that this works sporadically between restarts (and differs in behavior between using a link and an image). Any ideas on why that would be the case?

**Comment by achorein** [comment]
> that gets adds to "eas" in `app.json`. I seem to have to do it manually each time after build. Related to #1 (let me know if you want me to open a new issue)

as mention you juste have to add your projectId in app.json

> hmm I seem to experience that this works sporadically between restarts (and differs in behavior between using a link and an image). Any ideas on why that would be the case?

ok I'm going to test it in more depth on my side

**Comment by spencerc99** [comment]
@achorein amazing!! i will check this out tonight.

I also realized there's an interface distinction between the share intent triggering the opening of the app with the data and apps opening a pop-up screen to handle the share in-context. Do you know if that's supported with the react-native-share-intent library you are using / if there's a different solution for that?

**Comment by achorein** [comment]
as mentioned in #15 this project does not support custom view for ios, all the share intent must be handle into the app.

I close the issue, I think we have covered the subject of expo-router. feel free to re-open if problem persist.
