### ISSUE TITLE
Does this support custom views?

### ISSUE THREAD

**Issue by jkinggg** [achorein/expo-share-intent-demo#15]
Hi all,

Instead of opening my app on share, I would like to have a custom view similar to what's available in the react-native-share-menu library (https://github.com/Expensify/react-native-share-menu/blob/master/SHARE_EXTENSION_VIEW.md).

Is something like this possible with this library using expo plugins? If someone could outline the high-level architecture of how it would work, I can attempt to build it and create a PR.

-Johnny

**Comment by achorein** [comment]
The demo doesn't support custom view, the goal is to have a project without opening xcode :)

But you can try to customise the view by your own :

1. run `yarn prebuild` to got the generated "ios" folder
2. backup ios folder (cp -r ios ios.backup)
3. open the project into xcode and customize the view as you like
4. test it on simulator (yarn ios)
5. create a patch `diff -ur ios/ > ios.backup/` and clean unnecessary updates

after that we can look at what is needed to be implemented into a plugin. if you have something that other can use with small customization I would be happy to add it and create a PR on  [expo-config-plugin-ios-share-extension](https://github.com/timedtext/expo-config-plugin-ios-share-extension) where the change belong
