### ISSUE TITLE
useSharedIntent data arriving delayed to getStateFromPath function for deep linking

### ISSUE THREAD

**Issue by ChristopherGabba** [achorein/expo-share-intent-demo#20]
Good morning, I followed all of the steps provided:

1. Installed the two packages (react-native-receive-share-intent and expo-config-plugin-ios-share-extension)
2. Used patch package to make the changes you had in the patches folder
3. Placed the plugin code into app.json
4. Configured and built a new development build into the app

When I downloaded the development build, I'm still not seeing my app as a sharing option in any other app (safari, photos, reddit, instagram, etc.). 

I haven't implemented any code in my direct App.js file yet on dealing with the shared information (like the custom hook you built).  Is this required for my app to show up as an option? What steps am I missing? 

I'm first only looking at iOS.

**Comment by achorein** [comment]
👋 
for iOS the only thing to do to get the share menu in other app is to add the `expo-config-plugin-ios-share-extension` plugin in app.json :

```json
  "plugins": [
       "expo-config-plugin-ios-share-extension"
   ]
```

can you give some more info ?
- output of `npx react-native info`
- expo version (demo branch you use as exemple)
- is it working in simulator ? (`yarn prebuild && yarn ios`)

**Comment by ChristopherGabba** [comment]
> 👋 for iOS the only thing to do to get the share menu in other app is to add the `expo-config-plugin-ios-share-extension` plugin in app.json :
> 
> ```json
>   "plugins": [
>        "expo-config-plugin-ios-share-extension"
>    ]
> ```
> 
> can you give some more info ?
> 
> * output of `npx react-native info`
> * expo version (demo branch you use as exemple)
> * is it working in simulator ? (`yarn prebuild && yarn ios`)

I apologize, yesterday afternoon I managed to get it to show up. I was building off of the react-native ignite cli and I had the iOS and Android folders present, but wasn't using them. What I ended up doing was deleting the two folders and rebuilding the development build and boom it showed up. Can't really explain why, but maybe the folders were interfering with the extension. 

On another note, I'm working on the useShareIntent hook and converting it to typescript and standardizing outputs. I am also working on getting the deep linking working properly. I'll try to hit this thread with a reply so that we could improve on your currently fantastic expo extension work. Maybe we can add some wording to the read-me to get this working for others.

Thanks again,
Chris

**Comment by ChristopherGabba** [comment]
@achorein 
Currently the linked host that is passed into the app is in the format of "dataurl={*expo-scheme*}sharekey", and you make
 note of it in your instructions: 

<img width="862" alt="Screenshot 2023-10-02 at 12 11 30 PM" src="https://github.com/achorein/expo-share-intent-demo/assets/122328438/62deea19-8c2f-49a0-b87e-3e0a11ccceb5">

There is a timing issue that I'm struggling to work out. Essentially when you hit the 'Share to my app' icon from from your photos, safari, etc. The app navigates properly and you are able to deep link no problem to a screen that you would like. However, the useShareIntent hook takes a second or two to pass over the url data of the image. This causes a problem with the getStateFromPath function as the screen navigates to the nested screen and the data isn't available yet to be passed as a param. 



Here is what my linking config looks like:
```
const { shareIntent } = useShareIntent()
const prefixes = [Linking.createURL("")]
const config = {
  screens: {
    Tab: {
      screens: {
        Home: "home",
        FriendsList: "friendslist",
        Memories: "memories",
      },
    },
    Create: {
      path: "create",
      parse: {
        passedUrl: (passedUrl) => passedUrl,
      },
    },
  },
}

  const linking = {
    prefixes,
    config,
    getStateFromPath(path, config) {
      console.log("state path:", path, "config", config)
      if (path?.includes(`dataUrl={*my app config*}ShareKey`)) {
        return {
          routes: [{ name: "Create", params: { passedUrl: shareIntent?.filePath } }],
        }
      }
      return getStateFromPath(path, config)
    },
  }
```
As you can see, the `shareIntent?.filepath` is null for a second or two after the navigation, and no data is passed. 

To solve this problem, would be fantastic if the path outputed by the extension function `dataUrl={*my app config*}ShareKey` was more like `dataUrl={*my app config*}ShareKey{*filePathUrl*}`

That way prior to redirecting to the app, the data is ready to be passed to a deeply nested screen...
Thanks,
Chris

**Comment by ChristopherGabba** [comment]
@achorein 

Sorry another update... I was able to get the timing right but did not use the 'getStateFromPath' function as mentioned above. 

Instead I imported 
`import & as Linking from 'expo-linking'`
And then when I wanted to deep link into the app, I utilized 

`Linking.openURL(*my deep linking path*)` 

and I put this right next to the setShareIntent(XXXXX) functions within the useShareIntent hook and it jumps straight into the screen I want in the app.

So we made progress. Perhaps it's worth updating the README with this information. Just a thought...
Thanks,
Chris

**Comment by achorein** [comment]
I have an another approach for this, the `useShareIntent` hook should not be used at the linking level because is an async function as you mention. You should call it in the destination page ("Create" screen for you), this screen is responsable to show a loading state waiting for hook to finish (hook called in CreateScreen). if you use a common screen for content creation, just add a param to manage the "intent is coming". 

I find the openUrl trick counter-intuitive because we have to manage the linking in two places. I prefer to separate responsibilities.

when i have some time for that I will do a sample branch for react-navigation :)

**Comment by ChristopherGabba** [comment]
@achorein I agree that it's somewhat counter intuitive which is why I renamed the useSharedIntent() hook to be named 'receiveSharedValueIfAvailableAndDeepLinkToScreen()'

I tried that approach but there is a mounting issue. Deeply nested screens aren't loaded/mounted until they are targeted due to lazy loading of the navigators. If the useShareIntent hook is on that screen then the value you receive is null and it doesn't change as it was only mounted on the screen after the navigation. I'll try and play around with it more later but I couldn't get the { shareIntent } de-structured value to return anything. Maybe you can have more success....

All of these problems are solved if the initial "dataurl={expo-scheme}sharekey" value contains the file url. It would be super easy to use the getStateFromPath and still send the data.

**Comment by achorein** [comment]
Look at the shareIntent hook in the expo router branch https://github.com/achorein/expo-share-intent-demo/blob/expo49-expo-router/hooks/useShareIntent.js

I added a "refresh" when app become "active", that is need when using advanced linking on ios like you trying to do.
