### ISSUE TITLE
Share-Intent not working on iOS

### ISSUE THREAD

**Issue by huhulacolle** [achorein/expo-share-intent-demo#21]
(Excuse me for any errors, I don't speak English fluently and I'm using an automatic translator)

Hello, I have an issue with the iOS version of the app. I cloned, compiled with EAS, and installed it on an iPhone 8 with iOS 16.6.1. I wanted to test the sharing function. On Android, it works perfectly, but on iOS, it doesn't open the application, and no URL is displayed.

Does anyone know what the issue might be? Thank you in advance.

https://youtu.be/iXqrgdY4Xkk?si=ash4FQqZ9NTSliWX

**Comment by achorein** [comment]
it strange that the app doesn't show up after doing share intent on initial app.
make sure you have scheme configured into you app.json
```json
{
  "expo": {
    "scheme": "exposhareintentdemo"
  }
}
```

**Comment by huhulacolle** [comment]
@achorein 
It seems I had removed the slug when I cloned it, X). 
I put it back, and now it works. Thank you very much!!!
