### ISSUE TITLE
expo-modules-core:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by sevketaydogdu** [achorein/expo-share-intent-demo#26]
i integreted completely of your plugin.
Using `expo-router@2.0.14`, `expo@49.0.6`
When i try to `npx expo run:ios` it works well, but when i try to `npx expo run:android` gets error in my project.
After that i tried to run your demo project in branch 'expo router ' thats also giving same error.

Can you help me how to fix that ?
`
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (47, 20): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (62, 24): Unresolved reference: mutableListOf
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (67, 23): Unresolved reference: let
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (67, 29): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (68, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (78, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (79, 22): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (92, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (93, 34): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (102, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (103, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (115, 9): Unresolved reference: forEach
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (117, 30): Unresolved reference: it
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerWrapperDelegate.kt: (117, 82): Unresolved reference: it
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (12, 23): Class 'kotlin.reflect.KClass' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KClass.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (13, 23): Class 'kotlin.reflect.KType' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KType.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (16, 13): Class 'kotlin.reflect.KType' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KType.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (20, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (22, 11): Class 'kotlin.reflect.KType' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KType.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (31, 10): Class 'kotlin.reflect.KType' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KType.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (32, 24): Class 'kotlin.reflect.KClass' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KClass.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (32, 37): Class 'kotlin.reflect.KType' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KType.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (32, 42): Class 'kotlin.reflect.KClassifier' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KClassifier.class
e: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewTypeConverter.kt: (32, 56): Class 'kotlin.reflect.KClass' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/sevketaydogdu/.gradle/caches/transforms-3/11f8f99a2d35e2a3f61ea7b9f47c2be2/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KClass.class
`

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 26s
418 actionable tasks: 403 executed, 15 up-to-date
Error: /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/android/gradlew exited with non-zero code: 1
`

**Comment by binge6** [comment]
![image](https://github.com/achorein/expo-share-intent-demo/assets/40023013/db62ece1-cb5e-464f-a20b-b4e583ef9c7f) change kotlinVersion to you version.  `withAndroidBuildProperties.js`

**Comment by achorein** [comment]
as mention, the expo plugin used in the demo update the kotlin version to allow a success compilation. "1.8.10" should be ok, but you can try an other version.

to override the version you can also add it in the configuration file :

```json
  "plugins": [
      [
        "./plugins/withAndroidShareExtension/index",
        {
          ...
          "androidExtraBuildProperties": { 
             "kotlinVersion": "1.8.10"
          },
        }
      ],
  ],
  ```

@sevketaydogdu let me know which version was ok for you !
