### ISSUE TITLE
Taking a screenshot with iPhone and immediately sharing it using the share extension does not work

### ISSUE THREAD

**Issue by ChristopherGabba** [achorein/expo-share-intent-demo#28]
**Describe the bug**
Taking a screenshot of anything using any up to date iPhone (i've replicated it on iPhone 12 and iPhone 15) and immediately using the share extension does not open the app. And I cannot receive any data into the app to see if I can get the image file URL. Here is a video replicating the behavior:

**To Reproduce**
Video showing the issue:
https://github.com/achorein/expo-share-intent-demo/assets/122328438/c8416cfe-3fb1-4cc5-bf11-47db91a5045d

Please let me know if you have any questions. Here are my activation rules in app.json:
```javascript
      [
        "expo-config-plugin-ios-share-extension",
        {
          "activationRules": {
            "NSExtensionActivationSupportsText": true,
            "NSExtensionActivationSupportsWebURLWithMaxCount": 1,
            "NSExtensionActivationSupportsWebPageWithMaxCount": 1,
            "NSExtensionActivationSupportsImageWithMaxCount": 1,
            "NSExtensionActivationSupportsMovieWithMaxCount": 1
          }
        }
      ],
```
Everything else seems to work great (photo library, web pages, etc.).

Thanks,
Chris

**Environment**
```
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 562.66 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.7.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9862592
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.73.2 is now available (your project is running on v0.72.7).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.2
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.72.7
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos&platform=android".
```
**Additional context**
- expo version: 49.0.7
- target : iOS
- device : Real device
- type: Development and production build

**Comment by ChristopherGabba** [comment]
@achorein with my inexperience working directly with Swift. What is the step-by-step to update this? Is this something that you edit directly on ShareViewController.swift in x-code and then run npm install to get a new patch?

**Comment by ChristopherGabba** [comment]
@wodin  @achorein 
According to the issue mentioned [above](https://github.com/ajith-ab/react-native-receive-sharing-intent/issues/56.), you should simply paste the below code:


```swift
private func handleImages (content: NSExtensionItem, attachment: NSItemProvider, index: Int) {


   attachment.loadItem(forTypeIdentifier: imageContentType, options: nil) { [weak self] data, error in
     
     if error == nil, let this = self {

 
       var url: URL? = nil 


       if let dataURL = data as? URL { url = dataURL }
       else if let imageData = data as? UIImage { url = this.saveScreenshot(imageData) }

       let fileExtension = this.getExtension(from: url!, type: .image)
       let newName = UUID().uuidString
       let newPath = FileManager.default
         .containerURL(forSecurityApplicationGroupIdentifier: "group.\(this.hostAppBundleIdentifier)")!
         .appendingPathComponent("\(newName).\(fileExtension)")
       let copied = this.copyFile(at: url!, to: newPath)

       if(copied) {
         this.sharedMedia.append(SharedMediaFile(path: newPath.absoluteString, thumbnail: nil, duration: nil, type: .image))
       }
       
       // If this is the last item, save imagesData in userDefaults and redirect to host app
       if index == (content.attachments?.count)! - 1 {
         let userDefaults = UserDefaults(suiteName: "group.\(this.hostAppBundleIdentifier)")
         userDefaults?.set(this.toData(data: this.sharedMedia), forKey: this.sharedKey)
         userDefaults?.synchronize()
         this.redirectToHostApp(type: .media)
       }
       
     } else {
       self?.dismissWithError()
     }
   }
 }
 

  private func documentDirectoryPath () -> URL?  {
    
    let path = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
    return path.first
  }

  private func saveScreenshot(_ image: UIImage) -> URL?
  {
    var screenshotURL: URL? = nil
    if
    let screenshotData = image.pngData(),
    let screenshotPath = documentDirectoryPath()?.appendingPathComponent("Screenshot.png")
    {
   try? screenshotData.write(to: screenshotPath)
   screenshotURL = screenshotPath
    }
    return screenshotURL
} 

```

Directly into ShareViewController.swift under node modules?

Then run:
```npx patch-package react-native-receive-sharing-intent```

When I do that, it doesn't appear to add anything to the diff/patch file. 

Sorry, showing my inexperience dipping into the native code at all.... 

Thanks to both of you for the help...

**Comment by wodin** [comment]
> ShareViewController.swift under node modules

What package is this in? If I install `expo-config-plugin-ios-share-extension` and `react-native-receive-sharing-intent`, I don't find it under `node_modules`.

**Comment by ChristopherGabba** [comment]
@wodin I believe it is under `react-native-receive-sharing-intent`.... I could not find it when navigating node_modules via vscode, but when I opened "Finder" on my Mac and navigated down through node modules, I found it there.

**Comment by wodin** [comment]
It's definitely not there after just installing that package:
```console
$ find node_modules/ -type f -name ShareViewController.swift
$ 
```

So something must be generating it at some point. That complicates things. But then instead of using `patch-package` you might be able to use [`eas-build-post-install`](https://docs.expo.dev/build-reference/npm-hooks/) to patch or overwrite it.

If that doesn't work, it will be necessary to figure out where the file is coming from and patch *that*

**Comment by achorein** [comment]
We already have a patch for `react-native-receive-sharing-intent` using `patch-package`, IMO no need of eas-build-post-install.
But it sounds a little bit harder than excepted, patching `node_modules/react-native-receive-sharing-intent/ios/ReceiveSharingIntent.swift` give some compilation error and need a rework: 

```

❌  (node_modules/react-native-receive-sharing-intent/ios/ReceiveSharingIntent.swift:105:48)

  103 |     private func handleImages (content: NSExtensionItem, attachment: NSItemProvider, index: Int) {
  104 | 
> 105 |         attachment.loadItem(forTypeIdentifier: imageContentType, options: nil) { [weak self] data, error in
      |                                                ^ cannot find 'imageContentType' in scope
  106 |             
  107 |             if error == nil, let this = self {
  108 |         


❌  (node_modules/react-native-receive-sharing-intent/ios/ReceiveSharingIntent.swift:114:38)

  112 |             else if let imageData = data as? UIImage { url = this.saveScreenshot(imageData) }
  113 | 
> 114 |             let fileExtension = this.getExtension(from: url!, type: .image)
      |                                      ^ value of type 'ReceiveSharingIntent' has no member 'getExtension'
  115 |             let newName = UUID().uuidString
  116 |             let newPath = FileManager.default
  117 |                 .containerURL(forSecurityApplicationGroupIdentifier: "group.\(this.hostAppBundleIdentifier)")!


❌  (node_modules/react-native-receive-sharing-intent/ios/ReceiveSharingIntent.swift:114:70)

  112 |             else if let imageData = data as? UIImage { url = this.saveScreenshot(imageData) }
  113 | 
> 114 |             let fileExtension = this.getExtension(from: url!, type: .image)
      |                                                                      ^ cannot infer contextual base in reference to member 'image'
  115 |             let newName = UUID().uuidString
  116 |             let newPath = FileManager.default
  117 |                 .containerURL(forSecurityApplicationGroupIdentifier: "group.\(this.hostAppBundleIdentifier)")!


❌  (node_modules/react-native-receive-sharing-intent/ios/ReceiveSharingIntent.swift:114:70)

  112 |             else if let imageData = data as? UIImage { url = this.saveScreenshot(imageData) }
  113 | 
> 114 |             let fileExtension = this.getExtension(from: url!, type: .image)
      |                                                                      ^ cannot infer contextual base in reference to member 'image'
  115 |             let newName = UUID().uuidString
  116 |             let newPath = FileManager.default
  117 |                 .containerURL(forSecurityApplicationGroupIdentifier: "group.\(this.hostAppBundleIdentifier)")!
  ```

**Comment by ChristopherGabba** [comment]
@achorein 
Hey guys, just trying to help where I can. When I got to node_modules in finder and search "handleImages" (the function that was modified to support screenshots in the issue), Here is where it shows up:

![Screenshot 2024-01-21 at 7 42 20 AM](https://github.com/achorein/expo-share-intent-demo/assets/122328438/973d0d7b-f191-4145-9f50-1b6efc2ace36)

When I open the `writeShareExtensionOnFiles.js` file, I see the handle Images function. 

Looks like it is under the `expo-config-plugin-ios-share-extension`

**Comment by achorein** [comment]
@ChristopherGabba  oh nice, indeed, we should update the patch of expo-config-plugin-ios-share-extension here`patches/expo-config-plugin-ios-share-extension+0.0.4.patch`.
I will give a try when got some time.

**Comment by ChristopherGabba** [comment]
Thanks @achorein, would be awesome as this bug is still plaguing me!

**Comment by RamboWasReal** [comment]
same problem here

**Comment by achorein** [comment]
Here comes the new working patch :  [expo-config-plugin-ios-share-extension+0.0.4.patch](https://github.com/achorein/expo-share-intent-demo/files/14117103/expo-config-plugin-ios-share-extension%2B0.0.4.patch) ! 🚀 

- Replace patch here `patches/expo-config-plugin-ios-share-extension+0.0.4.patch`
- cleanup dependencies : `rm -fr node_modules && yarn install`
- cleanup prebuild : `yarn clean` (delete ios folder and run prebuild)
- restart project : `yarn ios`

@ChristopherGabba Let me know if it's working for you

**Comment by ChristopherGabba** [comment]
Thanks @achorein, trying it right now!

WIll keep you updated. So far I've:
1.  Installed the new patch in the patches folder
2. Run rm -fr node_modules && npm install (I'm using npm)
3. Compiling a new development build right now (using expo managed workflow)... should take about 10 mins
