### ISSUE TITLE
Sharing a Audio File ?

### ISSUE THREAD

**Issue by Onurr23** [achorein/expo-share-intent-demo#33]
Firstly, thank you for this great package. Is it possible to share one of recordings in ios device via our application ?

**Comment by achorein** [comment]
👋 
I think you can give a try with `NSExtensionActivationSupportsFileWithMaxCount`, in the `app.json` : 
```json
  "plugins": [
      [
        "expo-config-plugin-ios-share-extension",
        {
          "activationRules": {
             "NSExtensionActivationSupportsFileWithMaxCount": 1
          }
        }
      ],
  ],
```
not tested, but it should work. There is no filter for specific audio file on ios (more info [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nsextension/nsextensionattributes/nsextensionactivationrule))

**Comment by achorein** [comment]
feel free to reopen if this does not work

**Comment by delliott85** [comment]
I've tried adding configuration for files but my app doesn't appear on the share sheet in either Android or iOS when trying to share an audio file. I'm on Expo 50 and using the most recent version of your plugin

**Comment by Onurr23** [comment]
@achorein Thank you for your help. It worked.

**Comment by delliott85** [comment]
@Onurr23 did adding `NSExtensionActivationSupportsFileWithMaxCount` work for you? I can't seem to get it to work with audio files

**Comment by Onurr23** [comment]
> @Onurr23 did adding `NSExtensionActivationSupportsFileWithMaxCount` work for you? I can't seem to get it to work with audio files

Yes it worked. After i added `NSExtensionActivationSupportsFileWithMaxCount` to app.json and my app name started to be visible on share list
