### ISSUE TITLE
Cannot share multiple files at once

### ISSUE THREAD

**Issue by dr-zr** [achorein/expo-share-intent-demo#36]
**Describe the bug**
The extensions don't support sharing multiple supported files at once, even though [react-native-receive-sharing-intent demo](https://github.com/ajith-ab/react-native-receive-sharing-intent?tab=readme-ov-file#demo) shows that it's possible

**To Reproduce**
1. Add `image/*` in the array of supported files
2. Build app
3. Select multiple images from gallery
4. App won't be displayed

**Environment**
```sh
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 58.00 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.7.0
    path: ~/.nvm/versions/node/v20.7.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.7.0/bin/yarn
  npm:
    version: 10.1.0
    path: ~/.nvm/versions/node/v20.7.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.1
    path: /opt/homebrew/opt/openjdk/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

**Additional context**

- expo version: `expo@50.0.7`
- branch: `main` 
- target : `Android & iOS`
- device : `simulator & real device`
- type: `eas build --local` 
```json
"@react-navigation/native": "^6.1.9",
"@react-navigation/native-stack": "^6.9.17",
```

**Comment by achorein** [comment]
If I understand correctly, the application icon is not available in the sharing menu ?

what gallery application do you use in the android simulator ?

**Comment by achorein** [comment]
@dr-zr bug fixed on the corresponding PR, can you give it a try ?

**Comment by dr-zr** [comment]
@achorein You understood it correctly. I'll try now and edit this message with feedback
