### ISSUE TITLE
Can't build Expo project in Yarn workspace

### ISSUE THREAD

**Issue by crieggalder** [achorein/expo-share-intent-demo#39]
Thanks for the package! Running into an issue building with EAS and hope you can help. :)

**Describe the bug**
I'm in a Yarn 1.x workspace with a package.json at the root (./package.json) and my Expo project package.json at `./packages/app/package.json`.

`./package.json` postinstall: `"lerna bootstrap && patch-package",`
`./packages/app/package.json` postinstall: `"expo-yarn-workspaces postinstall"`
All packages from the demo installed in `./packages/app/packages.json`
patches folder located at `./packages/app/patches`

Here's my Xcode Logs error when building production iOS in EAS:

> /Users/expo/workingdir/build/packages/app/ios/Campfire.xcodeproj: error: The file "/Users/chris/go/campfire/packages/app/ios/ShareExtension/ShareExtension.entitlements" could not be opened. Verify the value of the CODE_SIGN_ENTITLEMENTS build setting for target "ShareExtension" is correct and that the file exists on disk. (in target 'ShareExtension' from project 'Campfire')

Manually installing from root and npx prebuild from `./packages/app` works fine, so I think for some reason EAS isn't building `ShareExtension.entitlements`.

**To Reproduce**
See above

** Environment **
give the output of the following command `npx react-native info`
>System:
  OS: macOS 13.5.1
  CPU: (8) arm64 Apple M1
  Memory: 81.69 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.12.1
    path: ~/.nvm/versions/node/v18.12.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.12.1/bin/yarn
  npm:
    version: 9.8.0
    path: ~/.nvm/versions/node/v18.12.1/bin/npm
  Watchman:
    version: 2023.03.27.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/chris/.gem/ruby/3.1.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.5
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/chris/.rubies/ruby-3.1.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Additional context**
- expo version (ex: 49): 50
- branch (ex: expo49-expo-router)
- target : Android / iOS: iOS
- device : simulator / real device: production EAS build
- type: local build / expo build: EAS build

**Comment by achorein** [comment]
🤔 strange behaviour, it's looks like a lerna missconfig.
can you try with the new package [expo-share-intent](https://github.com/achorein/expo-share-intent), shouldn't change anything but can simplifie project setup.
