### ISSUE TITLE
Supporting images, videos and files

### ISSUE THREAD

**Issue by kayode0x** [achorein/expo-share-intent-demo#4]
Hey, great work on this. I was wondering if it's ready to accepted files. I see the helper functions are implemented.
Also tried to work on this locally by adding

```
+                    NSExtensionActivationSupportsFileWithMaxCount: 1,
+                    NSExtensionActivationSupportsImageWithMaxCount: 1,
+                    NSExtensionActivationSupportsMovieWithMaxCount: 1,
```
to `/patches/expo-config-plugin-ios-share-extension+0.0.4.patch`, but it fails to patch the package. I need to edit this from the package in node_modules, but in there it's clean. Any help? thanks.

**Comment by achorein** [comment]
Thanks,

Yeah, that was the goal of this [PR](https://github.com/timedtext/expo-config-plugin-ios-share-extension/pull/11) on expo-config-plugin-ios-share-extension.

I think I can update my current patch to enable those plugin parameters
```json
  "plugins": [
     [
       "expo-config-plugin-ios-share-extension", 
       {
          "activationRules": {
               "NSExtensionActivationSupportsFileWithMaxCount": 1,
               "NSExtensionActivationSupportsImageWithMaxCount": 1,
               "NSExtensionActivationSupportsMovieWithMaxCount": 1,
          }
       }
     ]
  ],
```

**Comment by kayode0x** [comment]
Okay, I'll wait on the update. Or let me know if you need a hand, thanks.

**Comment by achorein** [comment]
Here the updated patch : [expo-config-plugin-ios-share-extension+0.0.4.patch](https://github.com/achorein/expo-share-intent-demo/files/12446688/expo-config-plugin-ios-share-extension%2B0.0.4.patch)

Just have to add plugins parameters mention above.
I need to do more tests, i got some issues to open app after using the share menu in the "Photos" simulator.

**Comment by kayode0x** [comment]
Sweet, thank you!

**Comment by achorein** [comment]
@kayode0x just added the code on the main branch, I had to modify the patch again. everything works fine, I updated the README. enjoy!
