### ISSUE TITLE
Using it on a separate repo, with android.

### ISSUE THREAD

**Issue by kayode0x** [achorein/expo-share-intent-demo#5]
I tried to use the logic here in a project to work with android, but the files in [plugins](https://github.com/achorein/expo-share-intent-demo/tree/main/plugins) are confusing.

How do I set this up? thanks again.

Expo: 48

**Comment by achorein** [comment]
in fact you have to copy "plugins" directory into your project, and add items mention in "Android ticks" section.

Manual configuration :
- add "expo-build-properties" package (`expo install expo-build-properties`)
- configure it in app.json :
    - kotlinVersion required by "react-native-receive-sharing-intent"
    - compileSdkVersion, targetSdkVersion, buildToolsVersion in order to comply with play stores rules
- add plugin "./plugins/withAndroidMainActivityAttributes" in app.json. The configuration directly call the file from "plugins" directory to update Android manifest MainActivity (we can add here `"android:launchMode": "singleTask"` if needed)
- update the "android" section of "app.json" to activate the share intent menu for specific mime type, you can also add `"image/*"` or simply `"*/*"`.

After that after every call of `expo prebuild` command, you have to apply the patch given in plugins directory. For that just run `patch -s -p0 < plugins/share-extension-patch-android.diff`.
In the demo project the patch is automatically called using yarn script.

is it any clearer for you.
I will work on a single plugin for android configuration to simplify integration

**Comment by kayode0x** [comment]
Thanks for the detailed response, but I figured it out myself.

What I did was create an expo plugin `withAndroidSharingIntent` to replace `patch -s -p0 < plugins/share-extension-patch-android.diff`

Let me know if you want me to push it here

**Comment by achorein** [comment]
Yes please, it will be the first step to full automation :)

**Comment by kayode0x** [comment]
Okay, please add a License first, then I'll create a PR

**Comment by achorein** [comment]
Just added Apache 2 Licence

**Comment by kayode0x** [comment]
I need permissions to push

**Comment by achorein** [comment]
You can just fork the repo and make a PR from that

**Comment by kayode0x** [comment]
Silly me, I forgot about that

**Comment by kayode0x** [comment]
@achorein I've tested my changes locally and it works fine. If you're in doubt, please test it yourself before mergin.
